# Generated by Django 5.2.1 on 2025-05-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='backups/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tamano', models.CharField(blank=True, max_length=50)),
                ('modelos_incluidos', models.TextField(blank=True)),
            ],
        ),
    ]
