# Generated by Django 5.2.1 on 2025-05-29 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='backup',
            name='modelos_incluidos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='backup',
            name='tamano',
            field=models.CharField(max_length=100),
        ),
    ]
