# Generated by Django 5.2.1 on 2025-06-26 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0007_alter_pedido_registrado_por_and_more'),
        ('cde', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocde',
            name='registrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cde_pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidoproductocde',
            name='area',
            field=models.CharField(default='No establecido', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidoproductocde',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cde.pedidocde'),
        ),
        migrations.AlterField(
            model_name='pedidoproductocde',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafeteria.productos'),
        ),
    ]
