# Generated by Django 5.2.1 on 2025-07-09 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0009_alter_pedidoproducto_producto'),
        ('cde', '0003_pedidocde_fecha_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoproductocde',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeteria.productos'),
        ),
    ]
