# Generated by Django 5.1.7 on 2025-07-19 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cde', '0004_alter_pedidoproductocde_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocde',
            name='fecha_estado',
        ),
        migrations.AlterField(
            model_name='pedidocde',
            name='fecha_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
