# Generated by Django 5.2.1 on 2025-06-04 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, max_length=30, null=True)),
                ('precio', models.PositiveBigIntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('proveedor', models.CharField(default='No establecido', max_length=100)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('unidad_medida', models.CharField(choices=[('Kilogramos', 'Kilogramos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas')], default='unidad', max_length=15)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
