# Generated by Django 5.2.1 on 2025-06-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='observacion',
        ),
        migrations.AddField(
            model_name='productos',
            name='presentacion',
            field=models.CharField(default='No establecido', max_length=50),
        ),
    ]
