# Generated by Django 5.2.1 on 2025-06-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_alter_productos_unidad_medida_pedido_pedidoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproducto',
            name='lugar',
            field=models.CharField(default='CCD', max_length=100),
        ),
    ]
