# Generated by Django 5.2.1 on 2025-06-10 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_pedidoproducto_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproducto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cafeteria.pedido'),
        ),
    ]
