# Generated by Django 5.2.1 on 2025-06-26 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0006_alter_productos_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='registrado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cafeteria_pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='area',
            field=models.CharField(blank=True, default='No establecido', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='lugar',
            field=models.CharField(blank=True, default='CCD', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cafeteria.pedido'),
        ),
        migrations.AlterField(
            model_name='pedidoproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cafeteria.productos'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='presentacion',
            field=models.CharField(blank=True, default='No establecido', max_length=50),
        ),
        migrations.AlterField(
            model_name='productos',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productos',
            name='unidad_medida',
            field=models.CharField(blank=True, choices=[('Kilogramos', 'Kilogramos'), ('Gramos', 'Gramos'), ('Litros', 'Litros'), ('Mililitros', 'Mililitros'), ('Onzas', 'Onzas'), ('Unidad', 'Unidad')], default='Unidad', max_length=15),
        ),
    ]
