# Generated by Django 5.2.1 on 2025-07-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0007_alter_pedido_registrado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_estado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
