# Generated by Django 5.1.7 on 2025-07-19 22:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0010_alter_pedido_fecha_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionCaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.PositiveIntegerField()),
                ('motivo', models.TextField()),
                ('fecha_devolucion', models.DateTimeField(default=django.utils.timezone.now)),
                ('devuelto_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('pedido_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='cafeteria.pedidoproducto')),
            ],
        ),
    ]
