# Generated by Django 5.1.7 on 2025-04-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(blank=True, default='No establecido', max_length=50, null=True),
        ),
    ]
