# Generated by Django 5.1.7 on 2025-04-27 13:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0003_pedido_articulo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pedido_articulo',
            new_name='PedidoArticulo',
        ),
    ]
