# Generated by Django 5.1.7 on 2025-04-27 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0005_alter_pedidoarticulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_articulos', to='papeleria.articulo'),
        ),
        migrations.AlterField(
            model_name='pedidoarticulo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_pedidos', to='papeleria.articulo'),
        ),
    ]
