# Generated by Django 5.1.7 on 2025-04-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0006_alter_pedidoarticulo_articulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoarticulo',
            name='tipo',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
