# Generated by Django 5.2.1 on 2025-05-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0008_remove_pedidoarticulo_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='observacion',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
