# Generated by Django 5.1.7 on 2025-05-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0010_articulo_proveedor_pedidoarticulo_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
