# Generated by Django 5.1.7 on 2025-05-26 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0011_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoarticulo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_articulo', to='papeleria.pedido'),
        ),
    ]
