# Generated by Django 5.1.7 on 2025-05-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0012_alter_pedidoarticulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoarticulo',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
