# Generated by Django 5.1.7 on 2025-06-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0013_alter_pedidoarticulo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
