# Generated by Django 5.2.1 on 2025-06-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0014_alter_articulo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='proveedor',
            field=models.CharField(default='No establecido', max_length=30),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='tipo',
            field=models.CharField(blank=True, default='No establecido', max_length=20, null=True),
        ),
    ]
