# Generated by Django 5.1.7 on 2025-06-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0016_alter_articulo_marca_alter_articulo_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.PositiveIntegerField(max_length=9),
        ),
    ]
