# Generated by Django 5.2.1 on 2025-06-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0017_alter_articulo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
