# Generated by Django 5.2.1 on 2025-06-27 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0018_alter_articulo_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='observacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
