# Generated by Django 5.2.1 on 2025-07-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0019_alter_articulo_cantidad_alter_articulo_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_estado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
