# Generated by Django 5.1.7 on 2025-04-29 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0007_alter_pedidoarticulo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoarticulo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='pedidoarticulo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedidoarticulo',
            name='fecha_pedido',
        ),
        migrations.AlterField(
            model_name='pedidoarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papeleria.articulo'),
        ),
        migrations.AlterField(
            model_name='pedidoarticulo',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pedidoarticulo',
            name='tipo',
            field=models.CharField(blank=True, default='No establecido', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='pendiente', max_length=20)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pedidoarticulo',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='papeleria.pedido'),
        ),
    ]
