# Generated by Django 5.2.1 on 2025-05-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papeleria', '0009_alter_articulo_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='proveedor',
            field=models.CharField(default='No establecido', max_length=100),
        ),
        migrations.AddField(
            model_name='pedidoarticulo',
            name='area',
            field=models.CharField(blank=True, default='No establecido', max_length=50, null=True),
        ),
    ]
