# Generated by Django 5.2.1 on 2025-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_alter_customuser_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='area',
            field=models.CharField(choices=[('Administrativa', 'Administrativa'), ('Comunicaciones', 'Comunicaciones'), ('Registros públicos', 'Registros públicos'), ('Gestión empresarial', 'Gestión empresarial'), ('Competitividad', 'Competitividad'), ('Presidencia', 'Presidencia'), ('Financiera', 'Financiera')], default='Administrativa', max_length=30),
        ),
    ]
