# Generated by Django 5.1.7 on 2025-05-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_customuser_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
    ]
