# Generated by Django 5.2.1 on 2025-05-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_customuser_fecha_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='module',
        ),
        migrations.AddField(
            model_name='customuser',
            name='acceso_caf',
            field=models.BooleanField(default=False, verbose_name='Acceso Cafetería'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='acceso_cde',
            field=models.BooleanField(default=False, verbose_name='Acceso Centro de Eventos'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='acceso_pap',
            field=models.BooleanField(default=False, verbose_name='Acceso Papelería'),
        ),
    ]
