# Generated by Django 5.1.7 on 2025-06-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_remove_customuser_module_customuser_acceso_caf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area',
            field=models.CharField(choices=[('Administrativa', 'Administrativa'), ('Registros públicos', 'Registros públicos'), ('Gestión empresarial', 'Gestión empresarial'), ('Competitividad', 'Competitividad'), ('Presidencia', 'Presidencia'), ('Financiera', 'Financiera')], default='Administrativa', max_length=30),
        ),
    ]
