# Generated by Django 5.2.1 on 2025-07-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
