# Generated by Django 5.2.1 on 2025-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0008_alter_customuser_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(default='No establecido', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
